use super::*;

const RISCV_LINUX_IO_SETUP_FOR_TEST: u64 = 0;
const RISCV_LINUX_IO_DESTROY_FOR_TEST: u64 = 1;
const RISCV_LINUX_IO_SUBMIT_FOR_TEST: u64 = 2;
const RISCV_LINUX_IO_CANCEL_FOR_TEST: u64 = 3;
const RISCV_LINUX_IO_GETEVENTS_FOR_TEST: u64 = 4;
const RISCV_LINUX_IO_PGETEVENTS_FOR_TEST: u64 = 292;
const RISCV_LINUX_LOOKUP_DCOOKIE_FOR_TEST: u64 = 18;
const RISCV_LINUX_NFSSERVCTL_FOR_TEST: u64 = 42;
const RISCV_LINUX_QUOTACTL_FOR_TEST: u64 = 60;
const RISCV_LINUX_MQ_OPEN_FOR_TEST: u64 = 180;
const RISCV_LINUX_MQ_UNLINK_FOR_TEST: u64 = 181;
const RISCV_LINUX_MQ_TIMEDSEND_FOR_TEST: u64 = 182;
const RISCV_LINUX_MQ_TIMEDRECEIVE_FOR_TEST: u64 = 183;
const RISCV_LINUX_MQ_NOTIFY_FOR_TEST: u64 = 184;
const RISCV_LINUX_MQ_GETSETATTR_FOR_TEST: u64 = 185;
const RISCV_LINUX_MSGGET_FOR_TEST: u64 = 186;
const RISCV_LINUX_MSGCTL_FOR_TEST: u64 = 187;
const RISCV_LINUX_MSGRCV_FOR_TEST: u64 = 188;
const RISCV_LINUX_MSGSND_FOR_TEST: u64 = 189;
const RISCV_LINUX_SEMGET_FOR_TEST: u64 = 190;
const RISCV_LINUX_SEMCTL_FOR_TEST: u64 = 191;
const RISCV_LINUX_SEMTIMEDOP_FOR_TEST: u64 = 192;
const RISCV_LINUX_SEMOP_FOR_TEST: u64 = 193;
const RISCV_LINUX_SHMGET_FOR_TEST: u64 = 194;
const RISCV_LINUX_SHMCTL_FOR_TEST: u64 = 195;
const RISCV_LINUX_SHMAT_FOR_TEST: u64 = 196;
const RISCV_LINUX_SHMDT_FOR_TEST: u64 = 197;
const RISCV_LINUX_ADD_KEY_FOR_TEST: u64 = 217;
const RISCV_LINUX_REQUEST_KEY_FOR_TEST: u64 = 218;
const RISCV_LINUX_KEYCTL_FOR_TEST: u64 = 219;
const RISCV_LINUX_CLONE_FOR_TEST: u64 = 220;
const RISCV_LINUX_REMAP_FILE_PAGES_FOR_TEST: u64 = 234;
const RISCV_LINUX_MIGRATE_PAGES_FOR_TEST: u64 = 238;
const RISCV_LINUX_MOVE_PAGES_FOR_TEST: u64 = 239;
const RISCV_LINUX_PERF_EVENT_OPEN_FOR_TEST: u64 = 241;
const RISCV_LINUX_FANOTIFY_INIT_FOR_TEST: u64 = 262;
const RISCV_LINUX_FANOTIFY_MARK_FOR_TEST: u64 = 263;
const RISCV_LINUX_NAME_TO_HANDLE_AT_FOR_TEST: u64 = 264;
const RISCV_LINUX_OPEN_BY_HANDLE_AT_FOR_TEST: u64 = 265;
const RISCV_LINUX_KCMP_FOR_TEST: u64 = 272;
const RISCV_LINUX_SECCOMP_FOR_TEST: u64 = 277;
const RISCV_LINUX_BPF_FOR_TEST: u64 = 280;
const RISCV_LINUX_USERFAULTFD_FOR_TEST: u64 = 282;
const RISCV_LINUX_PKEY_MPROTECT_FOR_TEST: u64 = 288;
const RISCV_LINUX_PKEY_ALLOC_FOR_TEST: u64 = 289;
const RISCV_LINUX_PKEY_FREE_FOR_TEST: u64 = 290;
const RISCV_LINUX_IO_URING_SETUP_FOR_TEST: u64 = 425;
const RISCV_LINUX_IO_URING_ENTER_FOR_TEST: u64 = 426;
const RISCV_LINUX_IO_URING_REGISTER_FOR_TEST: u64 = 427;
const RISCV_LINUX_OPEN_TREE_FOR_TEST: u64 = 428;
const RISCV_LINUX_MOVE_MOUNT_FOR_TEST: u64 = 429;
const RISCV_LINUX_FSOPEN_FOR_TEST: u64 = 430;
const RISCV_LINUX_FSCONFIG_FOR_TEST: u64 = 431;
const RISCV_LINUX_FSMOUNT_FOR_TEST: u64 = 432;
const RISCV_LINUX_FSPICK_FOR_TEST: u64 = 433;
const RISCV_LINUX_CLONE3_FOR_TEST: u64 = 435;
const RISCV_LINUX_PROCESS_MADVISE_FOR_TEST: u64 = 440;
const RISCV_LINUX_MOUNT_SETATTR_FOR_TEST: u64 = 442;
const RISCV_LINUX_QUOTACTL_FD_FOR_TEST: u64 = 443;
const RISCV_LINUX_LANDLOCK_CREATE_RULESET_FOR_TEST: u64 = 444;
const RISCV_LINUX_LANDLOCK_ADD_RULE_FOR_TEST: u64 = 445;
const RISCV_LINUX_LANDLOCK_RESTRICT_SELF_FOR_TEST: u64 = 446;
const RISCV_LINUX_PROCESS_MRELEASE_FOR_TEST: u64 = 448;
const RISCV_LINUX_FUTEX_WAITV_FOR_TEST: u64 = 449;
const RISCV_LINUX_SET_MEMPOLICY_HOME_NODE_FOR_TEST: u64 = 450;
const RISCV_LINUX_CACHESTAT_FOR_TEST: u64 = 451;
const RISCV_LINUX_MAP_SHADOW_STACK_FOR_TEST: u64 = 453;
const RISCV_LINUX_FUTEX_WAKE_FOR_TEST: u64 = 454;
const RISCV_LINUX_FUTEX_WAIT_FOR_TEST: u64 = 455;
const RISCV_LINUX_FUTEX_REQUEUE_FOR_TEST: u64 = 456;
const RISCV_LINUX_STATMOUNT_FOR_TEST: u64 = 457;
const RISCV_LINUX_LISTMOUNT_FOR_TEST: u64 = 458;
const RISCV_LINUX_LSM_GET_SELF_ATTR_FOR_TEST: u64 = 459;
const RISCV_LINUX_LSM_SET_SELF_ATTR_FOR_TEST: u64 = 460;
const RISCV_LINUX_LSM_LIST_MODULES_FOR_TEST: u64 = 461;
const RISCV_LINUX_MSEAL_FOR_TEST: u64 = 462;

#[test]
fn linux_table_unknown_numbers_return_enosys_and_record_request() {
    let mut state = RiscvSyscallState::new(0);

    assert_eq!(
        RiscvSyscallTable::new().handle_at_tick(
            RiscvSyscallRequest::new(0x8000, 9999, [0; 6]),
            &mut state,
            43
        ),
        Some(RiscvSyscallOutcome::Return {
            value: linux_error(RISCV_LINUX_ENOSYS)
        })
    );
    assert_eq!(state.program_break(), 0);
    assert!(state.guest_writes().is_empty());
    assert_eq!(
        state.unknown_syscalls(),
        &[RiscvUnknownSyscallRecord::new(0x8000, 9999, [0; 6], 43)]
    );
}

#[test]
fn linux_table_known_ni_syscalls_return_enosys_without_unknown_records() {
    let table = RiscvSyscallTable::new();
    let mut state = RiscvSyscallState::new(0);

    for (index, number) in [
        RISCV_LINUX_IO_SETUP_FOR_TEST,
        RISCV_LINUX_IO_DESTROY_FOR_TEST,
        RISCV_LINUX_IO_SUBMIT_FOR_TEST,
        RISCV_LINUX_IO_CANCEL_FOR_TEST,
        RISCV_LINUX_IO_GETEVENTS_FOR_TEST,
        RISCV_LINUX_LOOKUP_DCOOKIE_FOR_TEST,
        RISCV_LINUX_NFSSERVCTL_FOR_TEST,
        RISCV_LINUX_QUOTACTL_FOR_TEST,
        RISCV_LINUX_MQ_OPEN_FOR_TEST,
        RISCV_LINUX_MQ_UNLINK_FOR_TEST,
        RISCV_LINUX_MQ_TIMEDSEND_FOR_TEST,
        RISCV_LINUX_MQ_TIMEDRECEIVE_FOR_TEST,
        RISCV_LINUX_MQ_NOTIFY_FOR_TEST,
        RISCV_LINUX_MQ_GETSETATTR_FOR_TEST,
        RISCV_LINUX_MSGGET_FOR_TEST,
        RISCV_LINUX_MSGCTL_FOR_TEST,
        RISCV_LINUX_MSGRCV_FOR_TEST,
        RISCV_LINUX_MSGSND_FOR_TEST,
        RISCV_LINUX_SEMGET_FOR_TEST,
        RISCV_LINUX_SEMCTL_FOR_TEST,
        RISCV_LINUX_SEMTIMEDOP_FOR_TEST,
        RISCV_LINUX_SEMOP_FOR_TEST,
        RISCV_LINUX_SHMGET_FOR_TEST,
        RISCV_LINUX_SHMCTL_FOR_TEST,
        RISCV_LINUX_SHMAT_FOR_TEST,
        RISCV_LINUX_SHMDT_FOR_TEST,
        RISCV_LINUX_ADD_KEY_FOR_TEST,
        RISCV_LINUX_REQUEST_KEY_FOR_TEST,
        RISCV_LINUX_KEYCTL_FOR_TEST,
        RISCV_LINUX_CLONE_FOR_TEST,
        RISCV_LINUX_REMAP_FILE_PAGES_FOR_TEST,
        RISCV_LINUX_MIGRATE_PAGES_FOR_TEST,
        RISCV_LINUX_MOVE_PAGES_FOR_TEST,
        RISCV_LINUX_PERF_EVENT_OPEN_FOR_TEST,
        RISCV_LINUX_FANOTIFY_INIT_FOR_TEST,
        RISCV_LINUX_FANOTIFY_MARK_FOR_TEST,
        RISCV_LINUX_NAME_TO_HANDLE_AT_FOR_TEST,
        RISCV_LINUX_OPEN_BY_HANDLE_AT_FOR_TEST,
        RISCV_LINUX_KCMP_FOR_TEST,
        RISCV_LINUX_SECCOMP_FOR_TEST,
        RISCV_LINUX_BPF_FOR_TEST,
        RISCV_LINUX_USERFAULTFD_FOR_TEST,
        RISCV_LINUX_PKEY_MPROTECT_FOR_TEST,
        RISCV_LINUX_PKEY_ALLOC_FOR_TEST,
        RISCV_LINUX_PKEY_FREE_FOR_TEST,
        RISCV_LINUX_IO_PGETEVENTS_FOR_TEST,
        RISCV_LINUX_IO_URING_SETUP_FOR_TEST,
        RISCV_LINUX_IO_URING_ENTER_FOR_TEST,
        RISCV_LINUX_IO_URING_REGISTER_FOR_TEST,
        RISCV_LINUX_OPEN_TREE_FOR_TEST,
        RISCV_LINUX_MOVE_MOUNT_FOR_TEST,
        RISCV_LINUX_FSOPEN_FOR_TEST,
        RISCV_LINUX_FSCONFIG_FOR_TEST,
        RISCV_LINUX_FSMOUNT_FOR_TEST,
        RISCV_LINUX_FSPICK_FOR_TEST,
        RISCV_LINUX_CLONE3_FOR_TEST,
        RISCV_LINUX_PROCESS_MADVISE_FOR_TEST,
        RISCV_LINUX_MOUNT_SETATTR_FOR_TEST,
        RISCV_LINUX_QUOTACTL_FD_FOR_TEST,
        RISCV_LINUX_LANDLOCK_CREATE_RULESET_FOR_TEST,
        RISCV_LINUX_LANDLOCK_ADD_RULE_FOR_TEST,
        RISCV_LINUX_LANDLOCK_RESTRICT_SELF_FOR_TEST,
        RISCV_LINUX_PROCESS_MRELEASE_FOR_TEST,
        RISCV_LINUX_FUTEX_WAITV_FOR_TEST,
        RISCV_LINUX_SET_MEMPOLICY_HOME_NODE_FOR_TEST,
        RISCV_LINUX_CACHESTAT_FOR_TEST,
        RISCV_LINUX_MAP_SHADOW_STACK_FOR_TEST,
        RISCV_LINUX_FUTEX_WAKE_FOR_TEST,
        RISCV_LINUX_FUTEX_WAIT_FOR_TEST,
        RISCV_LINUX_FUTEX_REQUEUE_FOR_TEST,
        RISCV_LINUX_STATMOUNT_FOR_TEST,
        RISCV_LINUX_LISTMOUNT_FOR_TEST,
        RISCV_LINUX_LSM_GET_SELF_ATTR_FOR_TEST,
        RISCV_LINUX_LSM_SET_SELF_ATTR_FOR_TEST,
        RISCV_LINUX_LSM_LIST_MODULES_FOR_TEST,
        RISCV_LINUX_MSEAL_FOR_TEST,
    ]
    .into_iter()
    .enumerate()
    {
        let pc = 0x8000 + u64::try_from(index).unwrap() * 4;
        assert_eq!(
            table.handle_at_tick(RiscvSyscallRequest::new(pc, number, [0; 6]), &mut state, 37),
            Some(RiscvSyscallOutcome::Return {
                value: linux_error(RISCV_LINUX_ENOSYS)
            })
        );
    }
    assert!(state.unknown_syscalls().is_empty());
}
