use super::*;

const RISCV_LINUX_LOOKUP_DCOOKIE_FOR_TEST: u64 = 18;
const RISCV_LINUX_NFSSERVCTL_FOR_TEST: u64 = 42;
const RISCV_LINUX_CLONE_FOR_TEST: u64 = 220;
const RISCV_LINUX_PERF_EVENT_OPEN_FOR_TEST: u64 = 241;
const RISCV_LINUX_FANOTIFY_INIT_FOR_TEST: u64 = 262;
const RISCV_LINUX_FANOTIFY_MARK_FOR_TEST: u64 = 263;
const RISCV_LINUX_NAME_TO_HANDLE_AT_FOR_TEST: u64 = 264;
const RISCV_LINUX_OPEN_BY_HANDLE_AT_FOR_TEST: u64 = 265;
const RISCV_LINUX_KCMP_FOR_TEST: u64 = 272;
const RISCV_LINUX_SECCOMP_FOR_TEST: u64 = 277;
const RISCV_LINUX_BPF_FOR_TEST: u64 = 280;
const RISCV_LINUX_USERFAULTFD_FOR_TEST: u64 = 282;
const RISCV_LINUX_IO_URING_SETUP_FOR_TEST: u64 = 425;
const RISCV_LINUX_IO_URING_ENTER_FOR_TEST: u64 = 426;
const RISCV_LINUX_IO_URING_REGISTER_FOR_TEST: u64 = 427;
const RISCV_LINUX_OPEN_TREE_FOR_TEST: u64 = 428;
const RISCV_LINUX_MOVE_MOUNT_FOR_TEST: u64 = 429;
const RISCV_LINUX_FSOPEN_FOR_TEST: u64 = 430;
const RISCV_LINUX_FSCONFIG_FOR_TEST: u64 = 431;
const RISCV_LINUX_FSMOUNT_FOR_TEST: u64 = 432;
const RISCV_LINUX_FSPICK_FOR_TEST: u64 = 433;
const RISCV_LINUX_CLONE3_FOR_TEST: u64 = 435;
const RISCV_LINUX_PROCESS_MADVISE_FOR_TEST: u64 = 440;
const RISCV_LINUX_LANDLOCK_CREATE_RULESET_FOR_TEST: u64 = 444;
const RISCV_LINUX_LANDLOCK_ADD_RULE_FOR_TEST: u64 = 445;
const RISCV_LINUX_LANDLOCK_RESTRICT_SELF_FOR_TEST: u64 = 446;
const RISCV_LINUX_PROCESS_MRELEASE_FOR_TEST: u64 = 448;
const RISCV_LINUX_FUTEX_WAITV_FOR_TEST: u64 = 449;
const RISCV_LINUX_SET_MEMPOLICY_HOME_NODE_FOR_TEST: u64 = 450;
const RISCV_LINUX_CACHESTAT_FOR_TEST: u64 = 451;
const RISCV_LINUX_MAP_SHADOW_STACK_FOR_TEST: u64 = 453;
const RISCV_LINUX_FUTEX_WAKE_FOR_TEST: u64 = 454;
const RISCV_LINUX_FUTEX_WAIT_FOR_TEST: u64 = 455;
const RISCV_LINUX_FUTEX_REQUEUE_FOR_TEST: u64 = 456;
const RISCV_LINUX_STATMOUNT_FOR_TEST: u64 = 457;
const RISCV_LINUX_LISTMOUNT_FOR_TEST: u64 = 458;
const RISCV_LINUX_LSM_GET_SELF_ATTR_FOR_TEST: u64 = 459;
const RISCV_LINUX_LSM_SET_SELF_ATTR_FOR_TEST: u64 = 460;
const RISCV_LINUX_LSM_LIST_MODULES_FOR_TEST: u64 = 461;
const RISCV_LINUX_MSEAL_FOR_TEST: u64 = 462;

#[test]
fn linux_table_unknown_numbers_return_enosys_and_record_request() {
    let mut state = RiscvSyscallState::new(0);

    assert_eq!(
        RiscvSyscallTable::new().handle_at_tick(
            RiscvSyscallRequest::new(0x8000, 9999, [0; 6]),
            &mut state,
            43
        ),
        Some(RiscvSyscallOutcome::Return {
            value: linux_error(RISCV_LINUX_ENOSYS)
        })
    );
    assert_eq!(state.program_break(), 0);
    assert!(state.guest_writes().is_empty());
    assert_eq!(
        state.unknown_syscalls(),
        &[RiscvUnknownSyscallRecord::new(0x8000, 9999, [0; 6], 43)]
    );
}

#[test]
fn linux_table_known_ni_syscalls_return_enosys_without_unknown_records() {
    let table = RiscvSyscallTable::new();
    let mut state = RiscvSyscallState::new(0);

    for (pc, number) in [
        (0x8000, RISCV_LINUX_LOOKUP_DCOOKIE_FOR_TEST),
        (0x8004, RISCV_LINUX_NFSSERVCTL_FOR_TEST),
        (0x8008, RISCV_LINUX_CLONE_FOR_TEST),
        (0x800c, RISCV_LINUX_PERF_EVENT_OPEN_FOR_TEST),
        (0x8010, RISCV_LINUX_FANOTIFY_INIT_FOR_TEST),
        (0x8014, RISCV_LINUX_FANOTIFY_MARK_FOR_TEST),
        (0x8018, RISCV_LINUX_NAME_TO_HANDLE_AT_FOR_TEST),
        (0x801c, RISCV_LINUX_OPEN_BY_HANDLE_AT_FOR_TEST),
        (0x8020, RISCV_LINUX_KCMP_FOR_TEST),
        (0x8024, RISCV_LINUX_SECCOMP_FOR_TEST),
        (0x8028, RISCV_LINUX_BPF_FOR_TEST),
        (0x802c, RISCV_LINUX_USERFAULTFD_FOR_TEST),
        (0x8030, RISCV_LINUX_IO_URING_SETUP_FOR_TEST),
        (0x8034, RISCV_LINUX_IO_URING_ENTER_FOR_TEST),
        (0x8038, RISCV_LINUX_IO_URING_REGISTER_FOR_TEST),
        (0x803c, RISCV_LINUX_OPEN_TREE_FOR_TEST),
        (0x8040, RISCV_LINUX_MOVE_MOUNT_FOR_TEST),
        (0x8044, RISCV_LINUX_FSOPEN_FOR_TEST),
        (0x8048, RISCV_LINUX_FSCONFIG_FOR_TEST),
        (0x804c, RISCV_LINUX_FSMOUNT_FOR_TEST),
        (0x8050, RISCV_LINUX_FSPICK_FOR_TEST),
        (0x8054, RISCV_LINUX_CLONE3_FOR_TEST),
        (0x8058, RISCV_LINUX_PROCESS_MADVISE_FOR_TEST),
        (0x805c, RISCV_LINUX_LANDLOCK_CREATE_RULESET_FOR_TEST),
        (0x8060, RISCV_LINUX_LANDLOCK_ADD_RULE_FOR_TEST),
        (0x8064, RISCV_LINUX_LANDLOCK_RESTRICT_SELF_FOR_TEST),
        (0x8068, RISCV_LINUX_PROCESS_MRELEASE_FOR_TEST),
        (0x806c, RISCV_LINUX_FUTEX_WAITV_FOR_TEST),
        (0x8070, RISCV_LINUX_SET_MEMPOLICY_HOME_NODE_FOR_TEST),
        (0x8074, RISCV_LINUX_CACHESTAT_FOR_TEST),
        (0x8078, RISCV_LINUX_MAP_SHADOW_STACK_FOR_TEST),
        (0x807c, RISCV_LINUX_FUTEX_WAKE_FOR_TEST),
        (0x8080, RISCV_LINUX_FUTEX_WAIT_FOR_TEST),
        (0x8084, RISCV_LINUX_FUTEX_REQUEUE_FOR_TEST),
        (0x8088, RISCV_LINUX_STATMOUNT_FOR_TEST),
        (0x808c, RISCV_LINUX_LISTMOUNT_FOR_TEST),
        (0x8090, RISCV_LINUX_LSM_GET_SELF_ATTR_FOR_TEST),
        (0x8094, RISCV_LINUX_LSM_SET_SELF_ATTR_FOR_TEST),
        (0x8098, RISCV_LINUX_LSM_LIST_MODULES_FOR_TEST),
        (0x809c, RISCV_LINUX_MSEAL_FOR_TEST),
    ] {
        assert_eq!(
            table.handle_at_tick(RiscvSyscallRequest::new(pc, number, [0; 6]), &mut state, 37),
            Some(RiscvSyscallOutcome::Return {
                value: linux_error(RISCV_LINUX_ENOSYS)
            })
        );
    }
    assert!(state.unknown_syscalls().is_empty());
}
