[gpu_run]
workgroups = 2
compute_units = 2
memory_start = 4096
memory_size = 64
max_tick = 80
stats_format = "json"
power_format = "dsent-csv"
power_output = "../artifacts/gpu-power.csv"
nomali_output = "../artifacts/gpu-nomali.json"
output = "../artifacts/gpu.json"
stats_output = "../artifacts/gpu-stats.json"
dram_memory = true
data_cache_protocol = "msi"
global_loads = ["0x1000:4:4:4"]
global_stores = ["0x1004:4:4:4"]
memory_dumps = ["0x1000:16"]
