use super::{linux_error, RiscvSyscallRequest, RISCV_LINUX_EINVAL, RISCV_LINUX_EPERM};

pub(super) const RISCV_LINUX_SYSLOG: u64 = 116;

const RISCV_LINUX_SYSLOG_CLOSE: i32 = 0;
const RISCV_LINUX_SYSLOG_OPEN: i32 = 1;
const RISCV_LINUX_SYSLOG_READ: i32 = 2;
const RISCV_LINUX_SYSLOG_READ_ALL: i32 = 3;
const RISCV_LINUX_SYSLOG_READ_CLEAR: i32 = 4;
const RISCV_LINUX_SYSLOG_CLEAR: i32 = 5;
const RISCV_LINUX_SYSLOG_CONSOLE_OFF: i32 = 6;
const RISCV_LINUX_SYSLOG_CONSOLE_ON: i32 = 7;
const RISCV_LINUX_SYSLOG_CONSOLE_LEVEL: i32 = 8;
const RISCV_LINUX_SYSLOG_SIZE_UNREAD: i32 = 9;
const RISCV_LINUX_SYSLOG_SIZE_BUFFER: i32 = 10;

pub(super) fn syscall_syslog(request: RiscvSyscallRequest) -> u64 {
    match request.argument(0) as u32 as i32 {
        RISCV_LINUX_SYSLOG_CLOSE
        | RISCV_LINUX_SYSLOG_OPEN
        | RISCV_LINUX_SYSLOG_CLEAR
        | RISCV_LINUX_SYSLOG_CONSOLE_OFF
        | RISCV_LINUX_SYSLOG_CONSOLE_ON
        | RISCV_LINUX_SYSLOG_CONSOLE_LEVEL
        | RISCV_LINUX_SYSLOG_SIZE_UNREAD
        | RISCV_LINUX_SYSLOG_SIZE_BUFFER
        | RISCV_LINUX_SYSLOG_READ
        | RISCV_LINUX_SYSLOG_READ_ALL
        | RISCV_LINUX_SYSLOG_READ_CLEAR => linux_error(RISCV_LINUX_EPERM),
        _ => linux_error(RISCV_LINUX_EINVAL),
    }
}
