use super::*;

#[test]
fn rem6_gpu_run_reports_per_compute_unit_activity() {
    let output = Command::new(env!("CARGO_BIN_EXE_rem6"))
        .args([
            "gpu-run",
            "--workgroups",
            "5",
            "--compute-units",
            "2",
            "--wave-slots-per-compute-unit",
            "1",
            "--workgroup-cycles",
            "4",
            "--global-load",
            "0x3000:4:4:4",
            "--memory-start",
            "0x3000",
            "--memory-size",
            "64",
            "--max-tick",
            "80",
            "--stats-format",
            "json",
        ])
        .output()
        .unwrap();

    assert!(
        output.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let stdout = String::from_utf8(output.stdout).unwrap();
    let artifact: Value = serde_json::from_str(&stdout).unwrap();
    let simulation = artifact.get("simulation").unwrap();
    let compute_units = simulation
        .get("compute_unit_activity")
        .and_then(Value::as_array)
        .unwrap();
    assert!(stdout.contains("\"workgroup_completions\":5"));
    assert_eq!(
        compute_units[0]
            .get("workgroup_completions")
            .and_then(Value::as_u64),
        Some(3)
    );
    assert_eq!(
        compute_units[0].get("busy_cycles").and_then(Value::as_u64),
        Some(12)
    );
    assert_eq!(
        compute_units[1]
            .get("workgroup_completions")
            .and_then(Value::as_u64),
        Some(2)
    );
    assert_eq!(
        compute_units[1].get("busy_cycles").and_then(Value::as_u64),
        Some(8)
    );
    assert_eq!(
        simulation
            .get("workgroup_queue_wait_count")
            .and_then(Value::as_u64),
        Some(3)
    );
    assert_eq!(
        simulation
            .get("workgroup_queue_wait_ticks")
            .and_then(Value::as_u64),
        Some(16)
    );
    assert_eq!(
        simulation
            .get("max_workgroup_queue_wait_ticks")
            .and_then(Value::as_u64),
        Some(8)
    );
    assert_eq!(
        compute_units[0]
            .get("workgroup_queue_wait_count")
            .and_then(Value::as_u64),
        Some(2)
    );
    assert_eq!(
        compute_units[0]
            .get("workgroup_queue_wait_ticks")
            .and_then(Value::as_u64),
        Some(12)
    );
    assert_eq!(
        compute_units[0]
            .get("max_workgroup_queue_wait_ticks")
            .and_then(Value::as_u64),
        Some(8)
    );
    assert_eq!(
        compute_units[1]
            .get("workgroup_queue_wait_count")
            .and_then(Value::as_u64),
        Some(1)
    );
    assert_eq!(
        compute_units[1]
            .get("workgroup_queue_wait_ticks")
            .and_then(Value::as_u64),
        Some(4)
    );
    assert_eq!(
        compute_units[1]
            .get("max_workgroup_queue_wait_ticks")
            .and_then(Value::as_u64),
        Some(4)
    );
    assert_stat(
        &stdout,
        "sim.gpu_run.compute_unit.cu0.workgroup_completions",
        "Count",
        3,
        "monotonic",
    );
    assert_stat(
        &stdout,
        "sim.gpu_run.compute_unit.cu0.busy_cycles",
        "Cycle",
        12,
        "monotonic",
    );
    assert_stat(
        &stdout,
        "sim.gpu_run.compute_unit.cu0.first_started_at",
        "Tick",
        1,
        "monotonic",
    );
    assert_stat(
        &stdout,
        "sim.gpu_run.compute_unit.cu0.last_completed_at",
        "Tick",
        13,
        "monotonic",
    );
    assert_stat(
        &stdout,
        "sim.gpu_run.compute_unit.cu0.workgroup_queue_wait_count",
        "Count",
        2,
        "monotonic",
    );
    assert_stat(
        &stdout,
        "sim.gpu_run.compute_unit.cu0.workgroup_queue_wait_ticks",
        "Tick",
        12,
        "monotonic",
    );
    assert_stat(
        &stdout,
        "sim.gpu_run.compute_unit.cu0.max_workgroup_queue_wait_ticks",
        "Tick",
        8,
        "monotonic",
    );
    assert_stat(
        &stdout,
        "sim.gpu_run.compute_unit.cu1.workgroup_completions",
        "Count",
        2,
        "monotonic",
    );
    assert_stat(
        &stdout,
        "sim.gpu_run.compute_unit.cu1.busy_cycles",
        "Cycle",
        8,
        "monotonic",
    );
    assert_stat(
        &stdout,
        "sim.gpu_run.compute_unit.cu1.first_started_at",
        "Tick",
        1,
        "monotonic",
    );
    assert_stat(
        &stdout,
        "sim.gpu_run.compute_unit.cu1.last_completed_at",
        "Tick",
        9,
        "monotonic",
    );
    assert_stat(
        &stdout,
        "sim.gpu_run.compute_unit.cu1.workgroup_queue_wait_count",
        "Count",
        1,
        "monotonic",
    );
    assert_stat(
        &stdout,
        "sim.gpu_run.compute_unit.cu1.workgroup_queue_wait_ticks",
        "Tick",
        4,
        "monotonic",
    );
    assert_stat(
        &stdout,
        "sim.gpu_run.compute_unit.cu1.max_workgroup_queue_wait_ticks",
        "Tick",
        4,
        "monotonic",
    );
    assert_stat(
        &stdout,
        "sim.gpu_run.workgroup_queue_wait_count",
        "Count",
        3,
        "monotonic",
    );
    assert_stat(
        &stdout,
        "sim.gpu_run.workgroup_queue_wait_ticks",
        "Tick",
        16,
        "monotonic",
    );
    assert_stat(
        &stdout,
        "sim.gpu_run.max_workgroup_queue_wait_ticks",
        "Tick",
        8,
        "monotonic",
    );
}

#[test]
fn rem6_gpu_run_reports_per_compute_unit_memory_activity() {
    let output = Command::new(env!("CARGO_BIN_EXE_rem6"))
        .args([
            "gpu-run",
            "--workgroups",
            "3",
            "--compute-units",
            "2",
            "--wave-slots-per-compute-unit",
            "1",
            "--workgroup-cycles",
            "4",
            "--global-load",
            "0x3200:4:4:4",
            "--global-store",
            "0x3240:4:4:4",
            "--memory-start",
            "0x3200",
            "--memory-size",
            "128",
            "--max-tick",
            "80",
            "--stats-format",
            "json",
        ])
        .output()
        .unwrap();

    assert!(
        output.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let stdout = String::from_utf8(output.stdout).unwrap();
    let artifact: Value = serde_json::from_str(&stdout).unwrap();
    let simulation = artifact.get("simulation").unwrap();
    let compute_units = simulation
        .get("compute_unit_activity")
        .and_then(Value::as_array)
        .unwrap();
    assert_eq!(
        simulation
            .get("global_memory_requests")
            .and_then(Value::as_u64),
        Some(6)
    );
    assert_eq!(
        compute_units[0]
            .get("workgroup_completions")
            .and_then(Value::as_u64),
        Some(2)
    );
    assert_eq!(
        compute_units[0].get("busy_cycles").and_then(Value::as_u64),
        Some(8)
    );
    assert_eq!(
        compute_units[0]
            .get("coalesced_memory_accesses")
            .and_then(Value::as_u64),
        Some(4)
    );
    assert_eq!(
        compute_units[0]
            .get("global_memory_reads")
            .and_then(Value::as_u64),
        Some(2)
    );
    assert_eq!(
        compute_units[0]
            .get("global_memory_writes")
            .and_then(Value::as_u64),
        Some(2)
    );
    assert_eq!(
        compute_units[1]
            .get("workgroup_completions")
            .and_then(Value::as_u64),
        Some(1)
    );
    assert_eq!(
        compute_units[1].get("busy_cycles").and_then(Value::as_u64),
        Some(4)
    );
    assert_eq!(
        compute_units[1]
            .get("coalesced_memory_accesses")
            .and_then(Value::as_u64),
        Some(2)
    );
    assert_eq!(
        compute_units[1]
            .get("global_memory_reads")
            .and_then(Value::as_u64),
        Some(1)
    );
    assert_eq!(
        compute_units[1]
            .get("global_memory_writes")
            .and_then(Value::as_u64),
        Some(1)
    );
    assert_stat(
        &stdout,
        "sim.gpu_run.compute_unit.cu0.coalesced_memory_accesses",
        "Count",
        4,
        "monotonic",
    );
    assert_stat(
        &stdout,
        "sim.gpu_run.compute_unit.cu0.global_memory_reads",
        "Count",
        2,
        "monotonic",
    );
    assert_stat(
        &stdout,
        "sim.gpu_run.compute_unit.cu0.global_memory_writes",
        "Count",
        2,
        "monotonic",
    );
    assert_stat(
        &stdout,
        "sim.gpu_run.compute_unit.cu1.coalesced_memory_accesses",
        "Count",
        2,
        "monotonic",
    );
    assert_stat(
        &stdout,
        "sim.gpu_run.compute_unit.cu1.global_memory_reads",
        "Count",
        1,
        "monotonic",
    );
    assert_stat(
        &stdout,
        "sim.gpu_run.compute_unit.cu1.global_memory_writes",
        "Count",
        1,
        "monotonic",
    );
}

#[test]
fn rem6_gpu_run_merges_overlapping_wave_slots_for_compute_unit_busy_cycles() {
    let output = Command::new(env!("CARGO_BIN_EXE_rem6"))
        .args([
            "gpu-run",
            "--workgroups",
            "2",
            "--compute-units",
            "1",
            "--wave-slots-per-compute-unit",
            "2",
            "--workgroup-cycles",
            "4",
            "--global-load",
            "0x3400:4:4:4",
            "--memory-start",
            "0x3400",
            "--memory-size",
            "64",
            "--max-tick",
            "80",
            "--stats-format",
            "json",
        ])
        .output()
        .unwrap();

    assert!(
        output.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let stdout = String::from_utf8(output.stdout).unwrap();
    let artifact: Value = serde_json::from_str(&stdout).unwrap();
    let simulation = artifact.get("simulation").unwrap();
    let compute_units = simulation
        .get("compute_unit_activity")
        .and_then(Value::as_array)
        .unwrap();
    assert_eq!(
        compute_units[0]
            .get("workgroup_completions")
            .and_then(Value::as_u64),
        Some(2)
    );
    assert_eq!(
        compute_units[0].get("busy_cycles").and_then(Value::as_u64),
        Some(4)
    );
    assert_eq!(
        compute_units[0]
            .get("coalesced_memory_accesses")
            .and_then(Value::as_u64),
        Some(2)
    );
    assert_eq!(
        compute_units[0]
            .get("global_memory_reads")
            .and_then(Value::as_u64),
        Some(2)
    );
    assert_eq!(
        compute_units[0]
            .get("global_memory_writes")
            .and_then(Value::as_u64),
        Some(0)
    );
    assert_eq!(
        compute_units[0]
            .get("first_started_at")
            .and_then(Value::as_u64),
        Some(1)
    );
    assert_eq!(
        compute_units[0]
            .get("last_completed_at")
            .and_then(Value::as_u64),
        Some(5)
    );
    assert_stat(
        &stdout,
        "sim.gpu_run.compute_unit.cu0.busy_cycles",
        "Cycle",
        4,
        "monotonic",
    );
}

#[test]
fn rem6_gpu_run_omits_activity_window_stats_for_inactive_compute_units() {
    let output = Command::new(env!("CARGO_BIN_EXE_rem6"))
        .args([
            "gpu-run",
            "--workgroups",
            "1",
            "--compute-units",
            "2",
            "--wave-slots-per-compute-unit",
            "1",
            "--workgroup-cycles",
            "4",
            "--global-load",
            "0x3800:4:4:4",
            "--memory-start",
            "0x3800",
            "--memory-size",
            "64",
            "--max-tick",
            "80",
            "--stats-format",
            "json",
        ])
        .output()
        .unwrap();

    assert!(
        output.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let stdout = String::from_utf8(output.stdout).unwrap();
    let artifact: Value = serde_json::from_str(&stdout).unwrap();
    let simulation = artifact.get("simulation").unwrap();
    let compute_units = simulation
        .get("compute_unit_activity")
        .and_then(Value::as_array)
        .unwrap();
    assert_eq!(
        compute_units[1]
            .get("workgroup_completions")
            .and_then(Value::as_u64),
        Some(0)
    );
    assert_eq!(
        compute_units[1].get("busy_cycles").and_then(Value::as_u64),
        Some(0)
    );
    assert_eq!(
        compute_units[1]
            .get("coalesced_memory_accesses")
            .and_then(Value::as_u64),
        Some(0)
    );
    assert_eq!(
        compute_units[1]
            .get("global_memory_reads")
            .and_then(Value::as_u64),
        Some(0)
    );
    assert_eq!(
        compute_units[1]
            .get("global_memory_writes")
            .and_then(Value::as_u64),
        Some(0)
    );
    assert_eq!(
        compute_units[1].get("first_started_at").unwrap(),
        &Value::Null
    );
    assert_eq!(
        compute_units[1].get("last_completed_at").unwrap(),
        &Value::Null
    );
    assert_stat(
        &stdout,
        "sim.gpu_run.compute_unit.cu1.workgroup_completions",
        "Count",
        0,
        "monotonic",
    );
    assert_stat(
        &stdout,
        "sim.gpu_run.compute_unit.cu1.busy_cycles",
        "Cycle",
        0,
        "monotonic",
    );
    assert!(!stdout.contains("sim.gpu_run.compute_unit.cu1.first_started_at"));
    assert!(!stdout.contains("sim.gpu_run.compute_unit.cu1.last_completed_at"));
}
