use rem6_cpu::{BranchTargetKindCounts, BranchTargetProviderCounts};

use crate::branch_predictor_summary::{
    Rem6BranchPredictorCounterSummary, Rem6MultiperspectivePerceptronCounterSummary,
    Rem6TageScLBranchPredictorCounterSummary,
};
use crate::pipeline_stats::Rem6InOrderPipelineStageSummary;

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Rem6CoreSummary {
    pub(crate) cpu: u32,
    pub(crate) pc: u64,
    pub(crate) committed_instructions: u64,
    pub(crate) in_order_pipeline_cycles: u64,
    pub(crate) in_order_pipeline_in_flight: u64,
    pub(crate) in_order_pipeline_stage_widths: Rem6InOrderPipelineStageSummary,
    pub(crate) in_order_pipeline_stage_in_flight: Rem6InOrderPipelineStageSummary,
    pub(crate) in_order_pipeline_stage_max_in_flight: Rem6InOrderPipelineStageSummary,
    pub(crate) in_order_pipeline_stage_occupied_cycles: Rem6InOrderPipelineStageSummary,
    pub(crate) in_order_pipeline_stage_resource_blocked: Rem6InOrderPipelineStageSummary,
    pub(crate) in_order_pipeline_stage_resource_blocked_cycles: Rem6InOrderPipelineStageSummary,
    pub(crate) in_order_pipeline_stage_ordering_blocked: Rem6InOrderPipelineStageSummary,
    pub(crate) in_order_pipeline_stage_ordering_blocked_cycles: Rem6InOrderPipelineStageSummary,
    pub(crate) in_order_pipeline_stage_flushed: Rem6InOrderPipelineStageSummary,
    pub(crate) in_order_pipeline_stage_flushed_cycles: Rem6InOrderPipelineStageSummary,
    pub(crate) in_order_pipeline_stage_branch_prediction_flushed: Rem6InOrderPipelineStageSummary,
    pub(crate) in_order_pipeline_stage_branch_prediction_flushed_cycles:
        Rem6InOrderPipelineStageSummary,
    pub(crate) in_order_pipeline_retired: u64,
    pub(crate) in_order_pipeline_advanced: u64,
    pub(crate) in_order_pipeline_flushed: u64,
    pub(crate) in_order_pipeline_flush_cycles: u64,
    pub(crate) in_order_pipeline_resource_blocked: u64,
    pub(crate) in_order_pipeline_ordering_blocked: u64,
    pub(crate) in_order_pipeline_stall_cycles: u64,
    pub(crate) in_order_pipeline_fetch_wait_cycles: u64,
    pub(crate) in_order_pipeline_data_wait_cycles: u64,
    pub(crate) in_order_pipeline_execute_wait_cycles: u64,
    pub(crate) in_order_pipeline_branch_predictions: u64,
    pub(crate) in_order_pipeline_branch_mispredictions: u64,
    pub(crate) in_order_pipeline_conditional_branch_predictions: u64,
    pub(crate) in_order_pipeline_conditional_branch_predicted_taken: u64,
    pub(crate) in_order_pipeline_conditional_branch_mispredictions: u64,
    pub(crate) in_order_pipeline_branch_prediction_flushes: u64,
    pub(crate) in_order_pipeline_branch_prediction_flush_cycles: u64,
    pub(crate) in_order_pipeline_redirects: u64,
    pub(crate) in_order_pipeline_branch_speculation_predictions: u64,
    pub(crate) in_order_pipeline_branch_speculation_repairs: u64,
    pub(crate) in_order_pipeline_branch_speculation_removed_youngers: u64,
    pub(crate) in_order_pipeline_branch_speculation_max_pending: u64,
    pub(crate) branch_target_buffer_lookups: u64,
    pub(crate) branch_target_buffer_hits: u64,
    pub(crate) branch_target_buffer_misses: u64,
    pub(crate) branch_target_buffer_updates: u64,
    pub(crate) branch_target_buffer_evictions: u64,
    pub(crate) branch_target_buffer_mispredictions: u64,
    pub(crate) branch_target_buffer_predicted_taken_misses: u64,
    pub(crate) branch_target_buffer_mispredict_due_to_btb_miss: BranchTargetKindCounts,
    pub(crate) branch_predictor_lookups: BranchTargetKindCounts,
    pub(crate) branch_predictor_target_provider: BranchTargetProviderCounts,
    pub(crate) branch_predictor_committed: BranchTargetKindCounts,
    pub(crate) branch_predictor_mispredicted: BranchTargetKindCounts,
    pub(crate) branch_predictor_corrected: BranchTargetKindCounts,
    pub(crate) branch_predictor_target_wrong: BranchTargetKindCounts,
    pub(crate) branch_predictor_mispredict_due_to_predictor: BranchTargetKindCounts,
    pub(crate) branch_predictor_gshare: Rem6BranchPredictorCounterSummary,
    pub(crate) branch_predictor_bimode: Rem6BranchPredictorCounterSummary,
    pub(crate) branch_predictor_tournament: Rem6BranchPredictorCounterSummary,
    pub(crate) branch_predictor_tage_sc_l: Rem6TageScLBranchPredictorCounterSummary,
    pub(crate) branch_predictor_multiperspective_perceptron:
        Rem6MultiperspectivePerceptronCounterSummary,
    pub(crate) tournament_local_predictions: u64,
    pub(crate) tournament_global_predictions: u64,
    pub(crate) data_loads: u64,
    pub(crate) data_stores: u64,
    pub(crate) data_atomics: u64,
    pub(crate) data_load_bytes: u64,
    pub(crate) data_store_bytes: u64,
    pub(crate) data_atomic_bytes: u64,
    pub(crate) checker: Option<Rem6CheckerSummary>,
    pub(crate) registers: Vec<(u8, u64)>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Rem6CheckerSummary {
    pub(crate) checked_instructions: u64,
    pub(crate) mismatches: u64,
}
