use rem6_stats::{StatResetPolicy, StatsRegistry};

use super::{increment_stat, CliDataCacheSummary, Rem6CliError};

pub(super) fn emit_data_cache_summary_stats(
    stats: &mut StatsRegistry,
    prefix: &str,
    summary: &CliDataCacheSummary,
) -> Result<(), Rem6CliError> {
    increment_stat(
        stats,
        &format!("{prefix}.runs"),
        "Count",
        StatResetPolicy::Monotonic,
        summary.runs,
    )?;
    increment_stat(
        stats,
        &format!("{prefix}.msi.runs"),
        "Count",
        StatResetPolicy::Monotonic,
        summary.msi_runs,
    )?;
    increment_stat(
        stats,
        &format!("{prefix}.mesi.runs"),
        "Count",
        StatResetPolicy::Monotonic,
        summary.mesi_runs,
    )?;
    increment_stat(
        stats,
        &format!("{prefix}.moesi.runs"),
        "Count",
        StatResetPolicy::Monotonic,
        summary.moesi_runs,
    )?;
    increment_stat(
        stats,
        &format!("{prefix}.chi.runs"),
        "Count",
        StatResetPolicy::Monotonic,
        summary.chi_runs,
    )?;
    increment_stat(
        stats,
        &format!("{prefix}.cpu_responses"),
        "Count",
        StatResetPolicy::Monotonic,
        summary.cpu_responses,
    )?;
    increment_stat(
        stats,
        &format!("{prefix}.directory_decisions"),
        "Count",
        StatResetPolicy::Monotonic,
        summary.directory_decisions,
    )?;
    increment_stat(
        stats,
        &format!("{prefix}.dram_accesses"),
        "Count",
        StatResetPolicy::Monotonic,
        summary.dram_accesses,
    )?;
    increment_stat(
        stats,
        &format!("{prefix}.bank.accepted"),
        "Count",
        StatResetPolicy::Monotonic,
        summary.bank_accepted,
    )?;
    increment_stat(
        stats,
        &format!("{prefix}.bank.immediate_hits"),
        "Count",
        StatResetPolicy::Monotonic,
        summary.bank_immediate_hits,
    )?;
    increment_stat(
        stats,
        &format!("{prefix}.bank.scheduled_misses"),
        "Count",
        StatResetPolicy::Monotonic,
        summary.bank_scheduled_misses,
    )?;
    increment_stat(
        stats,
        &format!("{prefix}.bank.coalesced_misses"),
        "Count",
        StatResetPolicy::Monotonic,
        summary.bank_coalesced_misses,
    )?;
    Ok(())
}

pub(super) fn emit_data_cache_prefetch_summary_stats(
    stats: &mut StatsRegistry,
    prefix: &str,
    summary: &CliDataCacheSummary,
) -> Result<(), Rem6CliError> {
    increment_stat(
        stats,
        &format!("{prefix}.prefetch.identified"),
        "Count",
        StatResetPolicy::Monotonic,
        summary.prefetch_identified,
    )?;
    increment_stat(
        stats,
        &format!("{prefix}.prefetch.issued"),
        "Count",
        StatResetPolicy::Monotonic,
        summary.prefetch_issued,
    )?;
    increment_stat(
        stats,
        &format!("{prefix}.prefetch.useful"),
        "Count",
        StatResetPolicy::Monotonic,
        summary.prefetch_useful,
    )?;
    increment_stat(
        stats,
        &format!("{prefix}.prefetch.useful_but_miss"),
        "Count",
        StatResetPolicy::Monotonic,
        summary.prefetch_useful_but_miss,
    )?;
    increment_stat(
        stats,
        &format!("{prefix}.prefetch.unused"),
        "Count",
        StatResetPolicy::Monotonic,
        summary.prefetch_unused,
    )?;
    increment_stat(
        stats,
        &format!("{prefix}.prefetch.demand_mshr_misses"),
        "Count",
        StatResetPolicy::Monotonic,
        summary.prefetch_demand_mshr_misses,
    )?;
    increment_stat(
        stats,
        &format!("{prefix}.prefetch.hit_in_cache"),
        "Count",
        StatResetPolicy::Monotonic,
        summary.prefetch_hit_in_cache,
    )?;
    increment_stat(
        stats,
        &format!("{prefix}.prefetch.hit_in_mshr"),
        "Count",
        StatResetPolicy::Monotonic,
        summary.prefetch_hit_in_mshr,
    )?;
    increment_stat(
        stats,
        &format!("{prefix}.prefetch.hit_in_write_buffer"),
        "Count",
        StatResetPolicy::Monotonic,
        summary.prefetch_hit_in_write_buffer,
    )?;
    increment_stat(
        stats,
        &format!("{prefix}.prefetch.late"),
        "Count",
        StatResetPolicy::Monotonic,
        summary.prefetch_late,
    )?;
    if let Some(accuracy_ppm) = summary.prefetch_accuracy_ppm {
        increment_stat(
            stats,
            &format!("{prefix}.prefetch.accuracy_ppm"),
            "Ppm",
            StatResetPolicy::Monotonic,
            accuracy_ppm,
        )?;
    }
    if let Some(coverage_ppm) = summary.prefetch_coverage_ppm {
        increment_stat(
            stats,
            &format!("{prefix}.prefetch.coverage_ppm"),
            "Ppm",
            StatResetPolicy::Monotonic,
            coverage_ppm,
        )?;
    }
    increment_stat(
        stats,
        &format!("{prefix}.prefetch.span_page"),
        "Count",
        StatResetPolicy::Monotonic,
        summary.prefetch_span_page,
    )?;
    increment_stat(
        stats,
        &format!("{prefix}.prefetch.useful_span_page"),
        "Count",
        StatResetPolicy::Monotonic,
        summary.prefetch_useful_span_page,
    )?;
    increment_stat(
        stats,
        &format!("{prefix}.prefetch.in_cache"),
        "Count",
        StatResetPolicy::Monotonic,
        summary.prefetch_in_cache,
    )?;
    increment_stat(
        stats,
        &format!("{prefix}.prefetch.queue.enqueued"),
        "Count",
        StatResetPolicy::Monotonic,
        summary.prefetch_queue_enqueued,
    )?;
    increment_stat(
        stats,
        &format!("{prefix}.prefetch.queue.issued"),
        "Count",
        StatResetPolicy::Monotonic,
        summary.prefetch_queue_issued,
    )?;
    increment_stat(
        stats,
        &format!("{prefix}.prefetch.queue.dropped"),
        "Count",
        StatResetPolicy::Monotonic,
        summary.prefetch_queue_dropped,
    )?;
    increment_stat(
        stats,
        &format!("{prefix}.prefetch.translation_queue.enqueued"),
        "Count",
        StatResetPolicy::Monotonic,
        summary.prefetch_translation_queue_enqueued,
    )?;
    increment_stat(
        stats,
        &format!("{prefix}.prefetch.translation_queue.issued"),
        "Count",
        StatResetPolicy::Monotonic,
        summary.prefetch_translation_queue_issued,
    )?;
    increment_stat(
        stats,
        &format!("{prefix}.prefetch.translation_queue.translated"),
        "Count",
        StatResetPolicy::Monotonic,
        summary.prefetch_translation_queue_translated,
    )?;
    increment_stat(
        stats,
        &format!("{prefix}.prefetch.translation_queue.dropped"),
        "Count",
        StatResetPolicy::Monotonic,
        summary.prefetch_translation_queue_dropped,
    )?;
    Ok(())
}

pub(super) fn emit_gem5_cache_prefetcher_alias_stats(
    stats: &mut StatsRegistry,
    cache_prefix: &str,
    summary: &CliDataCacheSummary,
) -> Result<(), Rem6CliError> {
    increment_stat(
        stats,
        &format!("{cache_prefix}.prefetcher.pfIdentified"),
        "Count",
        StatResetPolicy::Monotonic,
        summary.prefetch_identified,
    )?;
    increment_stat(
        stats,
        &format!("{cache_prefix}.prefetcher.pfIssued"),
        "Count",
        StatResetPolicy::Monotonic,
        summary.prefetch_issued,
    )?;
    increment_stat(
        stats,
        &format!("{cache_prefix}.prefetcher.pfUseful"),
        "Count",
        StatResetPolicy::Monotonic,
        summary.prefetch_useful,
    )?;
    increment_stat(
        stats,
        &format!("{cache_prefix}.prefetcher.pfUsefulButMiss"),
        "Count",
        StatResetPolicy::Monotonic,
        summary.prefetch_useful_but_miss,
    )?;
    increment_stat(
        stats,
        &format!("{cache_prefix}.prefetcher.pfUnused"),
        "Count",
        StatResetPolicy::Monotonic,
        summary.prefetch_unused,
    )?;
    increment_stat(
        stats,
        &format!("{cache_prefix}.prefetcher.demandMshrMisses"),
        "Count",
        StatResetPolicy::Monotonic,
        summary.prefetch_demand_mshr_misses,
    )?;
    increment_stat(
        stats,
        &format!("{cache_prefix}.prefetcher.pfHitInCache"),
        "Count",
        StatResetPolicy::Monotonic,
        summary.prefetch_hit_in_cache,
    )?;
    increment_stat(
        stats,
        &format!("{cache_prefix}.prefetcher.pfHitInMSHR"),
        "Count",
        StatResetPolicy::Monotonic,
        summary.prefetch_hit_in_mshr,
    )?;
    increment_stat(
        stats,
        &format!("{cache_prefix}.prefetcher.pfHitInWB"),
        "Count",
        StatResetPolicy::Monotonic,
        summary.prefetch_hit_in_write_buffer,
    )?;
    increment_stat(
        stats,
        &format!("{cache_prefix}.prefetcher.pfLate"),
        "Count",
        StatResetPolicy::Monotonic,
        summary.prefetch_late,
    )?;
    increment_stat(
        stats,
        &format!("{cache_prefix}.prefetcher.pfSpanPage"),
        "Count",
        StatResetPolicy::Monotonic,
        summary.prefetch_span_page,
    )?;
    increment_stat(
        stats,
        &format!("{cache_prefix}.prefetcher.pfUsefulSpanPage"),
        "Count",
        StatResetPolicy::Monotonic,
        summary.prefetch_useful_span_page,
    )?;
    increment_stat(
        stats,
        &format!("{cache_prefix}.prefetcher.pfInCache"),
        "Count",
        StatResetPolicy::Monotonic,
        summary.prefetch_in_cache,
    )?;
    Ok(())
}
