use rem6_cpu::O3RuntimeFuLatencyClass;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(super) struct Rem6O3FuLatencyClassStatNames {
    pub(super) class: O3RuntimeFuLatencyClass,
    pub(super) instructions: &'static str,
    pub(super) cycles: &'static str,
    pub(super) max_cycles: &'static str,
    pub(super) min_cycles: &'static str,
    pub(super) avg_cycles: &'static str,
}

pub(super) const REM6_O3_FU_LATENCY_CLASS_STATS: [Rem6O3FuLatencyClassStatNames;
    O3RuntimeFuLatencyClass::COUNT] = [
    Rem6O3FuLatencyClassStatNames {
        class: O3RuntimeFuLatencyClass::ScalarIntegerMul,
        instructions: "event.fu_integer_mul_instructions",
        cycles: "event.fu_integer_mul_latency_cycles",
        max_cycles: "event.fu_integer_mul_latency_max_cycles",
        min_cycles: "event.fu_integer_mul_latency_min_cycles",
        avg_cycles: "event.fu_integer_mul_latency_avg_cycles",
    },
    Rem6O3FuLatencyClassStatNames {
        class: O3RuntimeFuLatencyClass::ScalarIntegerDiv,
        instructions: "event.fu_integer_div_instructions",
        cycles: "event.fu_integer_div_latency_cycles",
        max_cycles: "event.fu_integer_div_latency_max_cycles",
        min_cycles: "event.fu_integer_div_latency_min_cycles",
        avg_cycles: "event.fu_integer_div_latency_avg_cycles",
    },
    Rem6O3FuLatencyClassStatNames {
        class: O3RuntimeFuLatencyClass::ScalarFloatAdd,
        instructions: "event.fu_float_add_instructions",
        cycles: "event.fu_float_add_latency_cycles",
        max_cycles: "event.fu_float_add_latency_max_cycles",
        min_cycles: "event.fu_float_add_latency_min_cycles",
        avg_cycles: "event.fu_float_add_latency_avg_cycles",
    },
    Rem6O3FuLatencyClassStatNames {
        class: O3RuntimeFuLatencyClass::ScalarFloatCompare,
        instructions: "event.fu_float_compare_instructions",
        cycles: "event.fu_float_compare_latency_cycles",
        max_cycles: "event.fu_float_compare_latency_max_cycles",
        min_cycles: "event.fu_float_compare_latency_min_cycles",
        avg_cycles: "event.fu_float_compare_latency_avg_cycles",
    },
    Rem6O3FuLatencyClassStatNames {
        class: O3RuntimeFuLatencyClass::ScalarFloatMisc,
        instructions: "event.fu_float_misc_instructions",
        cycles: "event.fu_float_misc_latency_cycles",
        max_cycles: "event.fu_float_misc_latency_max_cycles",
        min_cycles: "event.fu_float_misc_latency_min_cycles",
        avg_cycles: "event.fu_float_misc_latency_avg_cycles",
    },
    Rem6O3FuLatencyClassStatNames {
        class: O3RuntimeFuLatencyClass::ScalarFloatMul,
        instructions: "event.fu_float_mul_instructions",
        cycles: "event.fu_float_mul_latency_cycles",
        max_cycles: "event.fu_float_mul_latency_max_cycles",
        min_cycles: "event.fu_float_mul_latency_min_cycles",
        avg_cycles: "event.fu_float_mul_latency_avg_cycles",
    },
    Rem6O3FuLatencyClassStatNames {
        class: O3RuntimeFuLatencyClass::ScalarFloatFma,
        instructions: "event.fu_float_fma_instructions",
        cycles: "event.fu_float_fma_latency_cycles",
        max_cycles: "event.fu_float_fma_latency_max_cycles",
        min_cycles: "event.fu_float_fma_latency_min_cycles",
        avg_cycles: "event.fu_float_fma_latency_avg_cycles",
    },
    Rem6O3FuLatencyClassStatNames {
        class: O3RuntimeFuLatencyClass::ScalarFloatDiv,
        instructions: "event.fu_float_div_instructions",
        cycles: "event.fu_float_div_latency_cycles",
        max_cycles: "event.fu_float_div_latency_max_cycles",
        min_cycles: "event.fu_float_div_latency_min_cycles",
        avg_cycles: "event.fu_float_div_latency_avg_cycles",
    },
    Rem6O3FuLatencyClassStatNames {
        class: O3RuntimeFuLatencyClass::ScalarFloatSqrt,
        instructions: "event.fu_float_sqrt_instructions",
        cycles: "event.fu_float_sqrt_latency_cycles",
        max_cycles: "event.fu_float_sqrt_latency_max_cycles",
        min_cycles: "event.fu_float_sqrt_latency_min_cycles",
        avg_cycles: "event.fu_float_sqrt_latency_avg_cycles",
    },
    Rem6O3FuLatencyClassStatNames {
        class: O3RuntimeFuLatencyClass::VectorIntegerMul,
        instructions: "event.fu_vector_integer_mul_instructions",
        cycles: "event.fu_vector_integer_mul_latency_cycles",
        max_cycles: "event.fu_vector_integer_mul_latency_max_cycles",
        min_cycles: "event.fu_vector_integer_mul_latency_min_cycles",
        avg_cycles: "event.fu_vector_integer_mul_latency_avg_cycles",
    },
    Rem6O3FuLatencyClassStatNames {
        class: O3RuntimeFuLatencyClass::VectorIntegerDiv,
        instructions: "event.fu_vector_integer_div_instructions",
        cycles: "event.fu_vector_integer_div_latency_cycles",
        max_cycles: "event.fu_vector_integer_div_latency_max_cycles",
        min_cycles: "event.fu_vector_integer_div_latency_min_cycles",
        avg_cycles: "event.fu_vector_integer_div_latency_avg_cycles",
    },
    Rem6O3FuLatencyClassStatNames {
        class: O3RuntimeFuLatencyClass::VectorFloatAdd,
        instructions: "event.fu_vector_float_add_instructions",
        cycles: "event.fu_vector_float_add_latency_cycles",
        max_cycles: "event.fu_vector_float_add_latency_max_cycles",
        min_cycles: "event.fu_vector_float_add_latency_min_cycles",
        avg_cycles: "event.fu_vector_float_add_latency_avg_cycles",
    },
    Rem6O3FuLatencyClassStatNames {
        class: O3RuntimeFuLatencyClass::VectorFloatCompare,
        instructions: "event.fu_vector_float_compare_instructions",
        cycles: "event.fu_vector_float_compare_latency_cycles",
        max_cycles: "event.fu_vector_float_compare_latency_max_cycles",
        min_cycles: "event.fu_vector_float_compare_latency_min_cycles",
        avg_cycles: "event.fu_vector_float_compare_latency_avg_cycles",
    },
    Rem6O3FuLatencyClassStatNames {
        class: O3RuntimeFuLatencyClass::VectorFloatMisc,
        instructions: "event.fu_vector_float_misc_instructions",
        cycles: "event.fu_vector_float_misc_latency_cycles",
        max_cycles: "event.fu_vector_float_misc_latency_max_cycles",
        min_cycles: "event.fu_vector_float_misc_latency_min_cycles",
        avg_cycles: "event.fu_vector_float_misc_latency_avg_cycles",
    },
    Rem6O3FuLatencyClassStatNames {
        class: O3RuntimeFuLatencyClass::VectorFloatMul,
        instructions: "event.fu_vector_float_mul_instructions",
        cycles: "event.fu_vector_float_mul_latency_cycles",
        max_cycles: "event.fu_vector_float_mul_latency_max_cycles",
        min_cycles: "event.fu_vector_float_mul_latency_min_cycles",
        avg_cycles: "event.fu_vector_float_mul_latency_avg_cycles",
    },
    Rem6O3FuLatencyClassStatNames {
        class: O3RuntimeFuLatencyClass::VectorFloatFma,
        instructions: "event.fu_vector_float_fma_instructions",
        cycles: "event.fu_vector_float_fma_latency_cycles",
        max_cycles: "event.fu_vector_float_fma_latency_max_cycles",
        min_cycles: "event.fu_vector_float_fma_latency_min_cycles",
        avg_cycles: "event.fu_vector_float_fma_latency_avg_cycles",
    },
    Rem6O3FuLatencyClassStatNames {
        class: O3RuntimeFuLatencyClass::VectorFloatDiv,
        instructions: "event.fu_vector_float_div_instructions",
        cycles: "event.fu_vector_float_div_latency_cycles",
        max_cycles: "event.fu_vector_float_div_latency_max_cycles",
        min_cycles: "event.fu_vector_float_div_latency_min_cycles",
        avg_cycles: "event.fu_vector_float_div_latency_avg_cycles",
    },
    Rem6O3FuLatencyClassStatNames {
        class: O3RuntimeFuLatencyClass::VectorFloatSqrt,
        instructions: "event.fu_vector_float_sqrt_instructions",
        cycles: "event.fu_vector_float_sqrt_latency_cycles",
        max_cycles: "event.fu_vector_float_sqrt_latency_max_cycles",
        min_cycles: "event.fu_vector_float_sqrt_latency_min_cycles",
        avg_cycles: "event.fu_vector_float_sqrt_latency_avg_cycles",
    },
];
