use crate::{
    AtomicMemoryOp, FloatRegister, Immediate, MemoryWidth, Register, RiscvCounterCsr,
    RiscvEnvironmentConfigCsrInstruction, RiscvFenceSet, RiscvFloatCsr, RiscvFloatRoundingMode,
    RiscvInterruptCsr, RiscvMachineTrapCsr, RiscvPseudoOp, RiscvStatusCsr, RiscvSupervisorTrapCsr,
    RiscvTranslationCsrInstruction, RiscvVectorMaskMode, VectorRegister,
};

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum RiscvInstruction {
    #[rustfmt::skip]
    Lui { rd: Register, imm: Immediate },
    Auipc {
        rd: Register,
        imm: Immediate,
    },
    Addi {
        rd: Register,
        rs1: Register,
        imm: Immediate,
    },
    Slti {
        rd: Register,
        rs1: Register,
        imm: Immediate,
    },
    Sltiu {
        rd: Register,
        rs1: Register,
        imm: Immediate,
    },
    Xori {
        rd: Register,
        rs1: Register,
        imm: Immediate,
    },
    Ori {
        rd: Register,
        rs1: Register,
        imm: Immediate,
    },
    Andi {
        rd: Register,
        rs1: Register,
        imm: Immediate,
    },
    Slli {
        rd: Register,
        rs1: Register,
        shamt: u8,
    },
    Srli {
        rd: Register,
        rs1: Register,
        shamt: u8,
    },
    Srai {
        rd: Register,
        rs1: Register,
        shamt: u8,
    },
    Addiw {
        rd: Register,
        rs1: Register,
        imm: Immediate,
    },
    Slliw {
        rd: Register,
        rs1: Register,
        shamt: u8,
    },
    Srliw {
        rd: Register,
        rs1: Register,
        shamt: u8,
    },
    Sraiw {
        rd: Register,
        rs1: Register,
        shamt: u8,
    },
    Add {
        rd: Register,
        rs1: Register,
        rs2: Register,
    },
    Sub {
        rd: Register,
        rs1: Register,
        rs2: Register,
    },
    Sll {
        rd: Register,
        rs1: Register,
        rs2: Register,
    },
    Slt {
        rd: Register,
        rs1: Register,
        rs2: Register,
    },
    Sltu {
        rd: Register,
        rs1: Register,
        rs2: Register,
    },
    Xor {
        rd: Register,
        rs1: Register,
        rs2: Register,
    },
    Srl {
        rd: Register,
        rs1: Register,
        rs2: Register,
    },
    Sra {
        rd: Register,
        rs1: Register,
        rs2: Register,
    },
    Or {
        rd: Register,
        rs1: Register,
        rs2: Register,
    },
    And {
        rd: Register,
        rs1: Register,
        rs2: Register,
    },
    Mul {
        rd: Register,
        rs1: Register,
        rs2: Register,
    },
    Mulh {
        rd: Register,
        rs1: Register,
        rs2: Register,
    },
    Mulhsu {
        rd: Register,
        rs1: Register,
        rs2: Register,
    },
    Mulhu {
        rd: Register,
        rs1: Register,
        rs2: Register,
    },
    Div {
        rd: Register,
        rs1: Register,
        rs2: Register,
    },
    Divu {
        rd: Register,
        rs1: Register,
        rs2: Register,
    },
    Rem {
        rd: Register,
        rs1: Register,
        rs2: Register,
    },
    Remu {
        rd: Register,
        rs1: Register,
        rs2: Register,
    },
    Mulw {
        rd: Register,
        rs1: Register,
        rs2: Register,
    },
    Divw {
        rd: Register,
        rs1: Register,
        rs2: Register,
    },
    Divuw {
        rd: Register,
        rs1: Register,
        rs2: Register,
    },
    Remw {
        rd: Register,
        rs1: Register,
        rs2: Register,
    },
    Remuw {
        rd: Register,
        rs1: Register,
        rs2: Register,
    },
    Addw {
        rd: Register,
        rs1: Register,
        rs2: Register,
    },
    Subw {
        rd: Register,
        rs1: Register,
        rs2: Register,
    },
    Sllw {
        rd: Register,
        rs1: Register,
        rs2: Register,
    },
    Srlw {
        rd: Register,
        rs1: Register,
        rs2: Register,
    },
    Sraw {
        rd: Register,
        rs1: Register,
        rs2: Register,
    },
    Beq {
        rs1: Register,
        rs2: Register,
        offset: Immediate,
    },
    Bne {
        rs1: Register,
        rs2: Register,
        offset: Immediate,
    },
    Blt {
        rs1: Register,
        rs2: Register,
        offset: Immediate,
    },
    Bge {
        rs1: Register,
        rs2: Register,
        offset: Immediate,
    },
    Bltu {
        rs1: Register,
        rs2: Register,
        offset: Immediate,
    },
    Bgeu {
        rs1: Register,
        rs2: Register,
        offset: Immediate,
    },
    Jal {
        rd: Register,
        offset: Immediate,
    },
    Jalr {
        rd: Register,
        rs1: Register,
        offset: Immediate,
    },
    VectorSetVli {
        rd: Register,
        rs1: Register,
        vtype: u64,
    },
    VectorSetIvli {
        rd: Register,
        avl: u8,
        vtype: u64,
    },
    VectorSetVl {
        rd: Register,
        rs1: Register,
        rs2: Register,
    },
    VectorAddVv {
        vd: VectorRegister,
        vs1: VectorRegister,
        vs2: VectorRegister,
        mask: RiscvVectorMaskMode,
    },
    VectorAddVx {
        vd: VectorRegister,
        vs2: VectorRegister,
        rs1: Register,
        mask: RiscvVectorMaskMode,
    },
    VectorAddVi {
        vd: VectorRegister,
        vs2: VectorRegister,
        imm: i8,
        mask: RiscvVectorMaskMode,
    },
    VectorSubVv {
        vd: VectorRegister,
        vs1: VectorRegister,
        vs2: VectorRegister,
    },
    VectorSubVx {
        vd: VectorRegister,
        vs2: VectorRegister,
        rs1: Register,
    },
    VectorReverseSubVx {
        vd: VectorRegister,
        vs2: VectorRegister,
        rs1: Register,
    },
    VectorReverseSubVi {
        vd: VectorRegister,
        vs2: VectorRegister,
        imm: i8,
    },
    VectorMinUnsignedVv {
        vd: VectorRegister,
        vs1: VectorRegister,
        vs2: VectorRegister,
    },
    VectorMinUnsignedVx {
        vd: VectorRegister,
        vs2: VectorRegister,
        rs1: Register,
    },
    VectorMinSignedVv {
        vd: VectorRegister,
        vs1: VectorRegister,
        vs2: VectorRegister,
    },
    VectorMinSignedVx {
        vd: VectorRegister,
        vs2: VectorRegister,
        rs1: Register,
    },
    VectorMaxUnsignedVv {
        vd: VectorRegister,
        vs1: VectorRegister,
        vs2: VectorRegister,
    },
    VectorMaxUnsignedVx {
        vd: VectorRegister,
        vs2: VectorRegister,
        rs1: Register,
    },
    VectorMaxSignedVv {
        vd: VectorRegister,
        vs1: VectorRegister,
        vs2: VectorRegister,
    },
    VectorMaxSignedVx {
        vd: VectorRegister,
        vs2: VectorRegister,
        rs1: Register,
    },
    VectorMultiplyLowVv {
        vd: VectorRegister,
        vs1: VectorRegister,
        vs2: VectorRegister,
    },
    VectorMultiplyLowVx {
        vd: VectorRegister,
        vs2: VectorRegister,
        rs1: Register,
    },
    VectorMultiplyHighUnsignedVv {
        vd: VectorRegister,
        vs1: VectorRegister,
        vs2: VectorRegister,
    },
    VectorMultiplyHighUnsignedVx {
        vd: VectorRegister,
        vs2: VectorRegister,
        rs1: Register,
    },
    VectorMultiplyHighSignedUnsignedVv {
        vd: VectorRegister,
        vs1: VectorRegister,
        vs2: VectorRegister,
    },
    VectorMultiplyHighSignedUnsignedVx {
        vd: VectorRegister,
        vs2: VectorRegister,
        rs1: Register,
    },
    VectorMultiplyHighSignedVv {
        vd: VectorRegister,
        vs1: VectorRegister,
        vs2: VectorRegister,
    },
    VectorMultiplyHighSignedVx {
        vd: VectorRegister,
        vs2: VectorRegister,
        rs1: Register,
    },
    VectorDivideUnsignedVv {
        vd: VectorRegister,
        vs1: VectorRegister,
        vs2: VectorRegister,
    },
    VectorDivideUnsignedVx {
        vd: VectorRegister,
        vs2: VectorRegister,
        rs1: Register,
    },
    VectorDivideSignedVv {
        vd: VectorRegister,
        vs1: VectorRegister,
        vs2: VectorRegister,
    },
    VectorDivideSignedVx {
        vd: VectorRegister,
        vs2: VectorRegister,
        rs1: Register,
    },
    VectorRemainderUnsignedVv {
        vd: VectorRegister,
        vs1: VectorRegister,
        vs2: VectorRegister,
    },
    VectorRemainderUnsignedVx {
        vd: VectorRegister,
        vs2: VectorRegister,
        rs1: Register,
    },
    VectorRemainderSignedVv {
        vd: VectorRegister,
        vs1: VectorRegister,
        vs2: VectorRegister,
    },
    VectorRemainderSignedVx {
        vd: VectorRegister,
        vs2: VectorRegister,
        rs1: Register,
    },
    VectorMergeVvm {
        vd: VectorRegister,
        vs2: VectorRegister,
        vs1: VectorRegister,
    },
    VectorMergeVxm {
        vd: VectorRegister,
        vs2: VectorRegister,
        rs1: Register,
    },
    VectorMergeVim {
        vd: VectorRegister,
        vs2: VectorRegister,
        imm: i8,
    },
    VectorCompressVm(VectorRegister, VectorRegister, VectorRegister),
    VectorNarrow(crate::vector::RiscvVectorNarrowInstruction),
    VectorAveraging(crate::vector_averaging::RiscvVectorAveragingInstruction),
    VectorFixedPointShift(crate::vector_fixed_point_shift::RiscvVectorFixedPointShiftInstruction),
    VectorReduction(crate::vector_reduction::RiscvVectorReductionInstruction),
    VectorSaturating(crate::vector_saturating::RiscvVectorSaturatingInstruction),
    VectorZeroExtend {
        vd: VectorRegister,
        vs2: VectorRegister,
        factor: crate::vector::RiscvVectorExtensionFactor,
        mask: RiscvVectorMaskMode,
    },
    VectorSignExtend {
        vd: VectorRegister,
        vs2: VectorRegister,
        factor: crate::vector::RiscvVectorExtensionFactor,
        mask: RiscvVectorMaskMode,
    },
    VectorMoveVv {
        vd: VectorRegister,
        vs1: VectorRegister,
    },
    VectorMoveVx {
        vd: VectorRegister,
        rs1: Register,
    },
    VectorMoveVi {
        vd: VectorRegister,
        imm: i8,
    },
    VectorScalarMove(crate::vector::RiscvVectorScalarMoveInstruction),
    VectorWholeMove(crate::vector::RiscvVectorWholeMoveInstruction),
    VectorMaskAndMm {
        vd: VectorRegister,
        vs2: VectorRegister,
        vs1: VectorRegister,
    },
    VectorMaskNandMm {
        vd: VectorRegister,
        vs2: VectorRegister,
        vs1: VectorRegister,
    },
    VectorMaskAndNotMm {
        vd: VectorRegister,
        vs2: VectorRegister,
        vs1: VectorRegister,
    },
    VectorMaskXorMm {
        vd: VectorRegister,
        vs2: VectorRegister,
        vs1: VectorRegister,
    },
    VectorMaskOrMm {
        vd: VectorRegister,
        vs2: VectorRegister,
        vs1: VectorRegister,
    },
    VectorMaskNorMm {
        vd: VectorRegister,
        vs2: VectorRegister,
        vs1: VectorRegister,
    },
    VectorMaskOrNotMm {
        vd: VectorRegister,
        vs2: VectorRegister,
        vs1: VectorRegister,
    },
    VectorMaskXnorMm {
        vd: VectorRegister,
        vs2: VectorRegister,
        vs1: VectorRegister,
    },
    VectorMaskReduction(crate::vector::RiscvVectorMaskReductionInstruction),
    VectorMaskPrefix(crate::vector::RiscvVectorMaskPrefixInstruction),
    VectorMaskIndex(crate::vector::RiscvVectorMaskIndexInstruction),
    VectorMaskEqualVv {
        vd: VectorRegister,
        vs1: VectorRegister,
        vs2: VectorRegister,
    },
    VectorMaskEqualVx {
        vd: VectorRegister,
        vs2: VectorRegister,
        rs1: Register,
    },
    VectorMaskEqualVi {
        vd: VectorRegister,
        vs2: VectorRegister,
        imm: i8,
    },
    VectorMaskNotEqualVv {
        vd: VectorRegister,
        vs1: VectorRegister,
        vs2: VectorRegister,
    },
    VectorMaskNotEqualVx {
        vd: VectorRegister,
        vs2: VectorRegister,
        rs1: Register,
    },
    VectorMaskNotEqualVi {
        vd: VectorRegister,
        vs2: VectorRegister,
        imm: i8,
    },
    VectorMaskLessUnsignedVv {
        vd: VectorRegister,
        vs1: VectorRegister,
        vs2: VectorRegister,
    },
    VectorMaskLessUnsignedVx {
        vd: VectorRegister,
        vs2: VectorRegister,
        rs1: Register,
    },
    VectorMaskLessSignedVv {
        vd: VectorRegister,
        vs1: VectorRegister,
        vs2: VectorRegister,
    },
    VectorMaskLessSignedVx {
        vd: VectorRegister,
        vs2: VectorRegister,
        rs1: Register,
    },
    VectorMaskLessEqualUnsignedVv {
        vd: VectorRegister,
        vs1: VectorRegister,
        vs2: VectorRegister,
    },
    VectorMaskLessEqualUnsignedVx {
        vd: VectorRegister,
        vs2: VectorRegister,
        rs1: Register,
    },
    VectorMaskLessEqualUnsignedVi {
        vd: VectorRegister,
        vs2: VectorRegister,
        imm: i8,
    },
    VectorMaskLessEqualSignedVv {
        vd: VectorRegister,
        vs1: VectorRegister,
        vs2: VectorRegister,
    },
    VectorMaskLessEqualSignedVx {
        vd: VectorRegister,
        vs2: VectorRegister,
        rs1: Register,
    },
    VectorMaskLessEqualSignedVi {
        vd: VectorRegister,
        vs2: VectorRegister,
        imm: i8,
    },
    VectorMaskGreaterUnsignedVx {
        vd: VectorRegister,
        vs2: VectorRegister,
        rs1: Register,
    },
    VectorMaskGreaterUnsignedVi {
        vd: VectorRegister,
        vs2: VectorRegister,
        imm: i8,
    },
    VectorMaskGreaterSignedVx {
        vd: VectorRegister,
        vs2: VectorRegister,
        rs1: Register,
    },
    VectorMaskGreaterSignedVi {
        vd: VectorRegister,
        vs2: VectorRegister,
        imm: i8,
    },
    VectorAndVv {
        vd: VectorRegister,
        vs1: VectorRegister,
        vs2: VectorRegister,
    },
    VectorAndVx {
        vd: VectorRegister,
        vs2: VectorRegister,
        rs1: Register,
    },
    VectorAndVi {
        vd: VectorRegister,
        vs2: VectorRegister,
        imm: i8,
    },
    VectorOrVv {
        vd: VectorRegister,
        vs1: VectorRegister,
        vs2: VectorRegister,
    },
    VectorOrVx {
        vd: VectorRegister,
        vs2: VectorRegister,
        rs1: Register,
    },
    VectorOrVi {
        vd: VectorRegister,
        vs2: VectorRegister,
        imm: i8,
    },
    VectorXorVv {
        vd: VectorRegister,
        vs1: VectorRegister,
        vs2: VectorRegister,
    },
    VectorXorVx {
        vd: VectorRegister,
        vs2: VectorRegister,
        rs1: Register,
    },
    VectorXorVi {
        vd: VectorRegister,
        vs2: VectorRegister,
        imm: i8,
    },
    VectorShiftLeftLogicalVv {
        vd: VectorRegister,
        vs1: VectorRegister,
        vs2: VectorRegister,
    },
    VectorShiftLeftLogicalVx {
        vd: VectorRegister,
        vs2: VectorRegister,
        rs1: Register,
    },
    VectorShiftLeftLogicalVi {
        vd: VectorRegister,
        vs2: VectorRegister,
        shamt: u8,
    },
    VectorShiftRightLogicalVv {
        vd: VectorRegister,
        vs1: VectorRegister,
        vs2: VectorRegister,
    },
    VectorShiftRightLogicalVx {
        vd: VectorRegister,
        vs2: VectorRegister,
        rs1: Register,
    },
    VectorShiftRightLogicalVi {
        vd: VectorRegister,
        vs2: VectorRegister,
        shamt: u8,
    },
    VectorShiftRightArithmeticVv {
        vd: VectorRegister,
        vs1: VectorRegister,
        vs2: VectorRegister,
    },
    VectorShiftRightArithmeticVx {
        vd: VectorRegister,
        vs2: VectorRegister,
        rs1: Register,
    },
    VectorShiftRightArithmeticVi {
        vd: VectorRegister,
        vs2: VectorRegister,
        shamt: u8,
    },
    VectorSlide(crate::vector::RiscvVectorSlideInstruction),
    VectorGather(crate::vector::RiscvVectorGatherInstruction),
    VectorFloat(crate::vector::RiscvVectorFloatInstruction),
    Load {
        rd: Register,
        rs1: Register,
        offset: Immediate,
        width: MemoryWidth,
        signed: bool,
    },
    FloatLoad {
        rd: FloatRegister,
        rs1: Register,
        offset: Immediate,
        width: MemoryWidth,
    },
    Store {
        rs1: Register,
        rs2: Register,
        offset: Immediate,
        width: MemoryWidth,
    },
    FloatStore {
        rs1: Register,
        rs2: FloatRegister,
        offset: Immediate,
        width: MemoryWidth,
    },
    FloatAddS {
        rd: FloatRegister,
        rs1: FloatRegister,
        rs2: FloatRegister,
        rounding_mode: RiscvFloatRoundingMode,
    },
    FloatSubS {
        rd: FloatRegister,
        rs1: FloatRegister,
        rs2: FloatRegister,
        rounding_mode: RiscvFloatRoundingMode,
    },
    FloatMulS {
        rd: FloatRegister,
        rs1: FloatRegister,
        rs2: FloatRegister,
        rounding_mode: RiscvFloatRoundingMode,
    },
    FloatDivS {
        rd: FloatRegister,
        rs1: FloatRegister,
        rs2: FloatRegister,
        rounding_mode: RiscvFloatRoundingMode,
    },
    FloatMultiplyAddS {
        rd: FloatRegister,
        rs1: FloatRegister,
        rs2: FloatRegister,
        rs3: FloatRegister,
        rounding_mode: RiscvFloatRoundingMode,
    },
    FloatMultiplySubtractS {
        rd: FloatRegister,
        rs1: FloatRegister,
        rs2: FloatRegister,
        rs3: FloatRegister,
        rounding_mode: RiscvFloatRoundingMode,
    },
    FloatNegativeMultiplySubtractS {
        rd: FloatRegister,
        rs1: FloatRegister,
        rs2: FloatRegister,
        rs3: FloatRegister,
        rounding_mode: RiscvFloatRoundingMode,
    },
    FloatNegativeMultiplyAddS {
        rd: FloatRegister,
        rs1: FloatRegister,
        rs2: FloatRegister,
        rs3: FloatRegister,
        rounding_mode: RiscvFloatRoundingMode,
    },
    FloatSqrtS {
        rd: FloatRegister,
        rs1: FloatRegister,
        rounding_mode: RiscvFloatRoundingMode,
    },
    FloatSignInjectS {
        rd: FloatRegister,
        rs1: FloatRegister,
        rs2: FloatRegister,
    },
    FloatSignInjectNegS {
        rd: FloatRegister,
        rs1: FloatRegister,
        rs2: FloatRegister,
    },
    FloatSignInjectXorS {
        rd: FloatRegister,
        rs1: FloatRegister,
        rs2: FloatRegister,
    },
    FloatMinS {
        rd: FloatRegister,
        rs1: FloatRegister,
        rs2: FloatRegister,
    },
    FloatMaxS {
        rd: FloatRegister,
        rs1: FloatRegister,
        rs2: FloatRegister,
    },
    FloatLessOrEqualS {
        rd: Register,
        rs1: FloatRegister,
        rs2: FloatRegister,
    },
    FloatLessThanS {
        rd: Register,
        rs1: FloatRegister,
        rs2: FloatRegister,
    },
    FloatEqualS {
        rd: Register,
        rs1: FloatRegister,
        rs2: FloatRegister,
    },
    FloatClassS {
        rd: Register,
        rs1: FloatRegister,
    },
    FloatMoveXFromS {
        rd: Register,
        rs1: FloatRegister,
    },
    FloatMoveSFromX {
        rd: FloatRegister,
        rs1: Register,
    },
    FloatConvertSFromW {
        rd: FloatRegister,
        rs1: Register,
        rounding_mode: RiscvFloatRoundingMode,
    },
    FloatConvertSFromWu {
        rd: FloatRegister,
        rs1: Register,
        rounding_mode: RiscvFloatRoundingMode,
    },
    FloatConvertSFromL {
        rd: FloatRegister,
        rs1: Register,
        rounding_mode: RiscvFloatRoundingMode,
    },
    FloatConvertSFromLu {
        rd: FloatRegister,
        rs1: Register,
        rounding_mode: RiscvFloatRoundingMode,
    },
    FloatConvertWFromS {
        rd: Register,
        rs1: FloatRegister,
        rounding_mode: RiscvFloatRoundingMode,
    },
    FloatConvertWuFromS {
        rd: Register,
        rs1: FloatRegister,
        rounding_mode: RiscvFloatRoundingMode,
    },
    FloatConvertLFromS {
        rd: Register,
        rs1: FloatRegister,
        rounding_mode: RiscvFloatRoundingMode,
    },
    FloatConvertLuFromS {
        rd: Register,
        rs1: FloatRegister,
        rounding_mode: RiscvFloatRoundingMode,
    },
    FloatConvertSFromD {
        rd: FloatRegister,
        rs1: FloatRegister,
    },
    FloatAddD {
        rd: FloatRegister,
        rs1: FloatRegister,
        rs2: FloatRegister,
        rounding_mode: RiscvFloatRoundingMode,
    },
    FloatSubD {
        rd: FloatRegister,
        rs1: FloatRegister,
        rs2: FloatRegister,
        rounding_mode: RiscvFloatRoundingMode,
    },
    FloatMulD {
        rd: FloatRegister,
        rs1: FloatRegister,
        rs2: FloatRegister,
        rounding_mode: RiscvFloatRoundingMode,
    },
    FloatDivD {
        rd: FloatRegister,
        rs1: FloatRegister,
        rs2: FloatRegister,
        rounding_mode: RiscvFloatRoundingMode,
    },
    FloatMultiplyAddD {
        rd: FloatRegister,
        rs1: FloatRegister,
        rs2: FloatRegister,
        rs3: FloatRegister,
        rounding_mode: RiscvFloatRoundingMode,
    },
    FloatMultiplySubtractD {
        rd: FloatRegister,
        rs1: FloatRegister,
        rs2: FloatRegister,
        rs3: FloatRegister,
        rounding_mode: RiscvFloatRoundingMode,
    },
    FloatNegativeMultiplySubtractD {
        rd: FloatRegister,
        rs1: FloatRegister,
        rs2: FloatRegister,
        rs3: FloatRegister,
        rounding_mode: RiscvFloatRoundingMode,
    },
    FloatNegativeMultiplyAddD {
        rd: FloatRegister,
        rs1: FloatRegister,
        rs2: FloatRegister,
        rs3: FloatRegister,
        rounding_mode: RiscvFloatRoundingMode,
    },
    FloatSqrtD {
        rd: FloatRegister,
        rs1: FloatRegister,
        rounding_mode: RiscvFloatRoundingMode,
    },
    FloatSignInjectD {
        rd: FloatRegister,
        rs1: FloatRegister,
        rs2: FloatRegister,
    },
    FloatSignInjectNegD {
        rd: FloatRegister,
        rs1: FloatRegister,
        rs2: FloatRegister,
    },
    FloatSignInjectXorD {
        rd: FloatRegister,
        rs1: FloatRegister,
        rs2: FloatRegister,
    },
    FloatMinD {
        rd: FloatRegister,
        rs1: FloatRegister,
        rs2: FloatRegister,
    },
    FloatMaxD {
        rd: FloatRegister,
        rs1: FloatRegister,
        rs2: FloatRegister,
    },
    FloatLessOrEqualD {
        rd: Register,
        rs1: FloatRegister,
        rs2: FloatRegister,
    },
    FloatLessThanD {
        rd: Register,
        rs1: FloatRegister,
        rs2: FloatRegister,
    },
    FloatEqualD {
        rd: Register,
        rs1: FloatRegister,
        rs2: FloatRegister,
    },
    FloatClassD {
        rd: Register,
        rs1: FloatRegister,
    },
    FloatMoveXFromD {
        rd: Register,
        rs1: FloatRegister,
    },
    FloatMoveDFromX {
        rd: FloatRegister,
        rs1: Register,
    },
    FloatConvertDFromW {
        rd: FloatRegister,
        rs1: Register,
        rounding_mode: RiscvFloatRoundingMode,
    },
    FloatConvertDFromWu {
        rd: FloatRegister,
        rs1: Register,
        rounding_mode: RiscvFloatRoundingMode,
    },
    FloatConvertDFromL {
        rd: FloatRegister,
        rs1: Register,
        rounding_mode: RiscvFloatRoundingMode,
    },
    FloatConvertDFromLu {
        rd: FloatRegister,
        rs1: Register,
        rounding_mode: RiscvFloatRoundingMode,
    },
    FloatConvertDFromS {
        rd: FloatRegister,
        rs1: FloatRegister,
    },
    FloatConvertWFromD {
        rd: Register,
        rs1: FloatRegister,
        rounding_mode: RiscvFloatRoundingMode,
    },
    FloatConvertWuFromD {
        rd: Register,
        rs1: FloatRegister,
        rounding_mode: RiscvFloatRoundingMode,
    },
    FloatConvertLFromD {
        rd: Register,
        rs1: FloatRegister,
        rounding_mode: RiscvFloatRoundingMode,
    },
    FloatConvertLuFromD {
        rd: Register,
        rs1: FloatRegister,
        rounding_mode: RiscvFloatRoundingMode,
    },
    LoadReserved {
        rd: Register,
        rs1: Register,
        width: MemoryWidth,
        acquire: bool,
        release: bool,
    },
    StoreConditional {
        rd: Register,
        rs1: Register,
        rs2: Register,
        width: MemoryWidth,
        acquire: bool,
        release: bool,
    },
    AtomicMemory {
        rd: Register,
        rs1: Register,
        rs2: Register,
        width: MemoryWidth,
        op: AtomicMemoryOp,
        acquire: bool,
        release: bool,
    },
    Fence {
        predecessor: RiscvFenceSet,
        successor: RiscvFenceSet,
        mode: u8,
    },
    FenceI,
    WaitForInterrupt,
    SupervisorReturn,
    MachineReturn,
    SfenceVma {
        rs1: Register,
        rs2: Register,
    },
    Gem5PseudoOp(RiscvPseudoOp),
    MachineInformationCsr(crate::csr::RiscvMachineInformationCsrInstruction),
    EnvironmentConfigCsr(RiscvEnvironmentConfigCsrInstruction),
    ReadCounterCsr {
        rd: Register,
        csr: RiscvCounterCsr,
    },
    ReadMachineCounterCsr {
        rd: Register,
        csr: RiscvCounterCsr,
    },
    WriteCounterCsr {
        rd: Register,
        csr: RiscvCounterCsr,
        rs1: Register,
    },
    SetCounterCsr {
        rd: Register,
        csr: RiscvCounterCsr,
        rs1: Register,
    },
    ClearCounterCsr {
        rd: Register,
        csr: RiscvCounterCsr,
        rs1: Register,
    },
    WriteCounterCsrImmediate {
        rd: Register,
        csr: RiscvCounterCsr,
        zimm: u8,
    },
    SetCounterCsrImmediate {
        rd: Register,
        csr: RiscvCounterCsr,
        zimm: u8,
    },
    ClearCounterCsrImmediate {
        rd: Register,
        csr: RiscvCounterCsr,
        zimm: u8,
    },
    ReadFloatCsr {
        rd: Register,
        csr: RiscvFloatCsr,
    },
    WriteFloatCsr {
        rd: Register,
        csr: RiscvFloatCsr,
        rs1: Register,
    },
    SetFloatCsr {
        rd: Register,
        csr: RiscvFloatCsr,
        rs1: Register,
    },
    ClearFloatCsr {
        rd: Register,
        csr: RiscvFloatCsr,
        rs1: Register,
    },
    WriteFloatCsrImmediate {
        rd: Register,
        csr: RiscvFloatCsr,
        zimm: u8,
    },
    SetFloatCsrImmediate {
        rd: Register,
        csr: RiscvFloatCsr,
        zimm: u8,
    },
    ClearFloatCsrImmediate {
        rd: Register,
        csr: RiscvFloatCsr,
        zimm: u8,
    },
    VectorFixedPointCsr(crate::csr::RiscvVectorFixedPointCsrInstruction),
    ReadStatusCsr {
        rd: Register,
        csr: RiscvStatusCsr,
    },
    WriteStatusCsr {
        rd: Register,
        csr: RiscvStatusCsr,
        rs1: Register,
    },
    SetStatusCsr {
        rd: Register,
        csr: RiscvStatusCsr,
        rs1: Register,
    },
    ClearStatusCsr {
        rd: Register,
        csr: RiscvStatusCsr,
        rs1: Register,
    },
    WriteStatusCsrImmediate {
        rd: Register,
        csr: RiscvStatusCsr,
        zimm: u8,
    },
    SetStatusCsrImmediate {
        rd: Register,
        csr: RiscvStatusCsr,
        zimm: u8,
    },
    ClearStatusCsrImmediate {
        rd: Register,
        csr: RiscvStatusCsr,
        zimm: u8,
    },
    ReadInterruptCsr {
        rd: Register,
        csr: RiscvInterruptCsr,
    },
    WriteInterruptCsr {
        rd: Register,
        csr: RiscvInterruptCsr,
        rs1: Register,
    },
    SetInterruptCsr {
        rd: Register,
        csr: RiscvInterruptCsr,
        rs1: Register,
    },
    ClearInterruptCsr {
        rd: Register,
        csr: RiscvInterruptCsr,
        rs1: Register,
    },
    WriteInterruptCsrImmediate {
        rd: Register,
        csr: RiscvInterruptCsr,
        zimm: u8,
    },
    SetInterruptCsrImmediate {
        rd: Register,
        csr: RiscvInterruptCsr,
        zimm: u8,
    },
    ClearInterruptCsrImmediate {
        rd: Register,
        csr: RiscvInterruptCsr,
        zimm: u8,
    },
    ReadMachineTrapCsr {
        rd: Register,
        csr: RiscvMachineTrapCsr,
    },
    WriteMachineTrapCsr {
        rd: Register,
        csr: RiscvMachineTrapCsr,
        rs1: Register,
    },
    SetMachineTrapCsr {
        rd: Register,
        csr: RiscvMachineTrapCsr,
        rs1: Register,
    },
    ClearMachineTrapCsr {
        rd: Register,
        csr: RiscvMachineTrapCsr,
        rs1: Register,
    },
    WriteMachineTrapCsrImmediate {
        rd: Register,
        csr: RiscvMachineTrapCsr,
        zimm: u8,
    },
    SetMachineTrapCsrImmediate {
        rd: Register,
        csr: RiscvMachineTrapCsr,
        zimm: u8,
    },
    ClearMachineTrapCsrImmediate {
        rd: Register,
        csr: RiscvMachineTrapCsr,
        zimm: u8,
    },
    ReadSupervisorTrapCsr {
        rd: Register,
        csr: RiscvSupervisorTrapCsr,
    },
    WriteSupervisorTrapCsr {
        rd: Register,
        csr: RiscvSupervisorTrapCsr,
        rs1: Register,
    },
    SetSupervisorTrapCsr {
        rd: Register,
        csr: RiscvSupervisorTrapCsr,
        rs1: Register,
    },
    ClearSupervisorTrapCsr {
        rd: Register,
        csr: RiscvSupervisorTrapCsr,
        rs1: Register,
    },
    WriteSupervisorTrapCsrImmediate {
        rd: Register,
        csr: RiscvSupervisorTrapCsr,
        zimm: u8,
    },
    SetSupervisorTrapCsrImmediate {
        rd: Register,
        csr: RiscvSupervisorTrapCsr,
        zimm: u8,
    },
    ClearSupervisorTrapCsrImmediate {
        rd: Register,
        csr: RiscvSupervisorTrapCsr,
        zimm: u8,
    },
    TranslationCsr(RiscvTranslationCsrInstruction),
    Ecall,
    Ebreak,
}
